from pathlib import Path
import re
p=Path('/mnt/data/unisocials_work')
# subadmin remove duplicate blocks
f=p/'subadmin.html'; s=f.read_text()
s=s.replace("          container.querySelectorAll('[data-account-toggle]').forEach(function(btn){\n            var archived=btn.getAttribute('data-archived')==='1'; btn.title=archived?'Unarchive influencer':'Archive influencer';\n            btn.addEventListener('click',function(){ var email=btn.getAttribute('data-email')||''; if(!email)return; if(!confirm((archived?'Unarchive':'Archive')+' influencer '+email+'?'))return; fetch('/api/admin/accounts/archive',{method:'POST',headers:authHeaders(),body:JSON.stringify({email:email,archived:!archived})}).then(function(r){return r.json();}).then(function(d){if(d&&d.success){showToast(archived?'Influencer unarchived':'Influencer archived');loadAllInfluencers();}else showToast((d&&d.error)||'Could not change influencer status',true);}).catch(function(){showToast('Network error changing influencer status',true);}); });\n          });\n",'')
s=s.replace("                '<button type=\"button\" class=\"admin-ticket-copy\" data-event-toggle=\"1\" data-event-id=\"' + esc(id) + '\" data-archived=\"' + (ev.archived ? '1' : '0') + '\" title=\"' + (ev.archived ? 'Unarchive event' : 'Archive event') + '\">' + (ev.archived ? '📦' : '🗃️') + '</button>' +\n                '<button type=\"button\" class=\"admin-ticket-copy\" data-event-toggle=\"1\" data-event-id=\"' + esc(id) + '\" data-archived=\"' + (ev.archived ? '1' : '0') + '\" title=\"' + (ev.archived ? 'Unarchive event' : 'Archive event') + '\">' + (ev.archived ? '📦' : '🗃️') + '</button>' +", "                '<button type=\"button\" class=\"admin-ticket-copy\" data-event-toggle=\"1\" data-event-id=\"' + esc(id) + '\" data-archived=\"' + (ev.archived ? '1' : '0') + '\" title=\"' + (ev.archived ? 'Unarchive event' : 'Archive event') + '\">' + (ev.archived ? '📦' : '🗃️') + '</button>' +",1)
s=s.replace("                (ev.archived ? '<span style=\"font-size:.68rem;color:#b71c1c;border:1px solid #f5c6cb;border-radius:999px;padding:2px 7px;\">ARCHIVED</span>' : '') +\n                (ev.archived ? '<span style=\"font-size:.68rem;color:#b71c1c;border:1px solid #f5c6cb;border-radius:999px;padding:2px 7px;\">ARCHIVED</span>' : '') +", "                (ev.archived ? '<span style=\"font-size:.68rem;color:#b71c1c;border:1px solid #f5c6cb;border-radius:999px;padding:2px 7px;\">ARCHIVED</span>' : '') +",1)
f.write_text(s)

# admin replace specific render snippets with toggles
f=p/'admin.html'; s=f.read_text()
# influencer action line
old="                '</div><div style=\"display:flex;gap:6px;align-items:flex-start;\"><button class=\"admin-ticket-copy\" onclick=\"resetManagedPassword(\\\'' + esc(u.email || '') + '\\\')\" title=\"Reset password\">🔑</button><button class=\"admin-ticket-copy\" onclick=\"deleteInfluencer(\\\'' + esc(u.email || '') + '\\\')\" title=\"Remove influencer\" style=\"color:#B71C1C;border-color:#F5C6CB;\">✕</button></div></div>';"
new="                '</div><div style=\"display:flex;gap:6px;align-items:flex-start;\"><button class=\"admin-ticket-copy\" onclick=\"resetManagedPassword(\\\'' + esc(u.email || '') + '\\\')\" title=\"Reset password\">🔑</button><button class=\"admin-ticket-copy\" onclick=\"deleteInfluencer(\\\'' + esc(u.email || '') + '\\\')\" title=\"Remove influencer\" style=\"color:#B71C1C;border-color:#F5C6CB;\">✕</button><button type=\"button\" class=\"admin-ticket-copy\" data-account-toggle=\"1\" data-email=\"' + esc(u.email || '') + '\" data-archived=\"' + (u.archived ? '1' : '0') + '\" title=\"' + (u.archived ? 'Unarchive influencer' : 'Archive influencer') + '\">' + (u.archived ? '📦' : '🗃️') + '</button></div></div>';"
if old not in s: print('influencer line mismatch')
else: s=s.replace(old,new,1)
# staff line
old="                '<div style=\"display:flex;flex-direction:column;gap:4px;\"><div><strong>'+esc(u.name||'—')+'</strong> <span style=\"font-size:.72rem;color:var(--text-3);\">'+esc(u.email||'')+'</span></div>'+                '<span style=\"font-size:.72rem;color:var(--accent);font-weight:700;\">'+label+'</span></div>'+                '<div style=\"display:flex;gap:6px;align-items:flex-start;\"><button class=\"admin-ticket-copy\" onclick=\"resetManagedPassword(\\\''+esc(u.email||'')+'\\\')\" title=\"Reset password\">🔑</button><button class=\"admin-ticket-copy\" onclick=\"deleteStaffAccount(\\\''+esc(u.email||'')+'\\\')\" title=\"Remove account\" style=\"color:#B71C1C;border-color:#F5C6CB;\">✕</button></div></div>';"
new="                '<div style=\"display:flex;flex-direction:column;gap:4px;\"><div><strong>'+esc(u.name||'—')+'</strong>'+(u.archived?'<span style=\"font-size:.68rem;color:#b71c1c;border:1px solid #f5c6cb;border-radius:999px;padding:2px 7px;margin-left:6px;\">ARCHIVED</span>':'')+' <span style=\"font-size:.72rem;color:var(--text-3);\">'+esc(u.email||'')+'</span></div>'+                '<span style=\"font-size:.72rem;color:var(--accent);font-weight:700;\">'+label+'</span></div>'+                '<div style=\"display:flex;gap:6px;align-items:flex-start;\"><button class=\"admin-ticket-copy\" onclick=\"resetManagedPassword(\\\''+esc(u.email||'')+'\\\')\" title=\"Reset password\">🔑</button><button class=\"admin-ticket-copy\" onclick=\"deleteStaffAccount(\\\''+esc(u.email||'')+'\\\')\" title=\"Remove account\" style=\"color:#B71C1C;border-color:#F5C6CB;\">✕</button><button type=\"button\" class=\"admin-ticket-copy\" data-account-toggle=\"1\" data-email=\"' + esc(u.email || '') + '\" data-archived=\"' + (u.archived ? '1' : '0') + '\" title=\"' + (u.archived ? 'Unarchive account' : 'Archive account') + '\">' + (u.archived ? '📦' : '🗃️') + '</button></div></div>';"
if old not in s: print('staff line mismatch')
else: s=s.replace(old,new,1)
# subadmin badge already inserted, influencer badge yes.
f.write_text(s)
