from pathlib import Path
p=Path('/mnt/data/event_edit/admin.html');s=p.read_text()
helper='''      var editingEventId = '';\n\n      window.cancelEditEvent = function() {\n        editingEventId = '';\n        var btn=document.getElementById('eventSubmitBtn'); if(btn) btn.textContent='➕ Add Event';\n        var cancel=document.getElementById('eventCancelEditBtn'); if(cancel) cancel.style.display='none';\n        ['evName','evPrice','evVIPPrice','evVVIPPrice','evTablePrice','evDate','evTime','evVenue','evDesc','evTags','evIncludedRegular','evIncludedVip','evIncludedVVIP','evIncludedTable'].forEach(function(id){var e=document.getElementById(id);if(e)e.value='';});\n        var uni=document.getElementById('evUniversity');if(uni)uni.value='';\n        if(typeof updateUniCategories==='function')updateUniCategories();\n        if(typeof clearEventImage==='function')clearEventImage();\n      };\n\n      window.editManagedEvent = function(eventId) {\n        if(!eventId)return;\n        fetch('/api/events',{headers:authHeaders()}).then(function(r){if(r.status===401)throw new Error('Unauthorized');return r.json();}).then(function(data){\n          var events=(data&&data.success&&data.events)||[];\n          var ev=events.find(function(x){return String(x.id||x._id||'')===String(eventId);});\n          if(!ev)throw new Error('Event not found');\n          editingEventId=String(ev.id||eventId);\n          var set=function(id,v){var e=document.getElementById(id);if(e)e.value=(v==null?'':v);};\n          set('evName',ev.name);set('evPrice',ev.price);set('evVIPPrice',ev.vipPrice);set('evVVIPPrice',ev.vvipPrice);set('evTablePrice',ev.tablePrice);\n          set('evDate',ev.date);set('evTime',ev.time);set('evVenue',ev.venue);set('evDesc',ev.description);\n          set('evTags',Array.isArray(ev.tags)?ev.tags.join(', '):ev.tags);\n          set('evIncludedRegular',ev.includedRegular);set('evIncludedVip',ev.includedVip);set('evIncludedVVIP',ev.includedVVIP);set('evIncludedTable',ev.includedTable);\n          var uni=document.getElementById('evUniversity');if(uni){uni.value=ev.universityId||'';if(typeof updateUniCategories==='function')updateUniCategories();var cat=document.getElementById('evCategory');if(cat)cat.value=ev.category||'General';}\n          selectedEventImage=ev.image||'';if(typeof setEventImagePreview==='function')setEventImagePreview(selectedEventImage);\n          var btn=document.getElementById('eventSubmitBtn');if(btn)btn.textContent='💾 Save Event Changes';\n          var cancel=document.getElementById('eventCancelEditBtn');if(cancel)cancel.style.display='inline-flex';\n          var panel=document.getElementById('panel-events');if(panel)panel.scrollIntoView({behavior:'smooth',block:'start'});\n          showToast('Editing “'+(ev.name||'event')+'”. Update the fields and save.');\n        }).catch(function(err){showToast(err.message||'Could not load that event.',true);});\n      };\n\n'''
s=s.replace('window.addEventItem = function() {',helper+'window.addEventItem = function() {',1)
pos=s.find('window.addEventItem = function() {')
obj=s.find('var ev = {',pos)
name=s.find('name:',obj)
if obj!=-1 and name!=-1 and 'id: editingEventId' not in s[obj:name]:
 s=s[:name]+'id: editingEventId || undefined,\n          '+s[name:]
s=s.replace('clearEventImage();\n            loadManagedEvents();','clearEventImage();\n            cancelEditEvent();\n            loadManagedEvents();',1)
p.write_text(s)
