services:
  - type: web
    name: unisocials
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: WHATSAPP_FLOAT_NUMBER
        value: 2348122104576
      - key: WHATSAPP_ORDER_NUMBER
        value: 2348122104576
      - key: BANK_NAME
        value: GTBank
      - key: BANK_ACCOUNT_NAME
        value: UNN Socials
      - key: BANK_ACCOUNT_NUMBER
        value: 0123456789
      - key: USSD_CODE
        value: "*123*456*"
      - key: CONTACT_EMAIL
        value: events@unnsocials.com
      - key: FORMSUBMIT_KEY
        value: 8d51333da2a9cfabfb087ffb615b7963
      - key: REDIRECT_URL
        value: https://unnsocials.com/thank-you.html

