/*
UNN Socials — Node.js static file server + dynamic config generator
Serves the static site and injects environment variables into config.js
at request time, so Render env vars are picked up without a build step.
*/

const http = require('http');
const fs = require('fs');
const path = require('path');

const PORT = process.env.PORT || 3000;
const PUBLIC_DIR = __dirname;

// Default configuration values (overridden by environment variables on Render)
const defaults = {
  WHATSAPP_FLOAT_NUMBER: '2348122104576',
  WHATSAPP_ORDER_NUMBER: '2348122104576',
  FLUTTERWAVE_PUBLIC_KEY: 'FSTOU9su2xlF8UU8wU05kNvqEbI8v47S',
  FLUTTERWAVE_BANK_NAME: 'Flutterwave MfB (formerly ok mfb)',
  FLUTTERWAVE_ACCOUNT_NUMBER: '9707788756',
  CONTACT_EMAIL: 'support.sbiamautos@gmail.com',
  FORMSUBMIT_KEY: 'support.sbiamautos@gmail.com',
  REDIRECT_URL: 'https://unisocials.onrender.com/thank-you.html'
};

function getConfig() {
  const cfg = {};
  for (const [key, val] of Object.entries(defaults)) {
    cfg[key] = process.env[key] !== undefined ? process.env[key] : val;
  }
  return cfg;
}

const MIME_TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.png': 'image/png',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.webp': 'image/webp',
  '.txt': 'text/plain; charset=utf-8',
  '.map': 'application/json; charset=utf-8'
};

const server = http.createServer((req, res) => {
  // Dynamically serve config.js with env var values
  if (req.url === '/config.js' || req.url === '/config.js?') {
    const cfg = getConfig();
    const js = `/* Generated by server.js from environment variables */\n` +
      `window.SITE_CONFIG = ${JSON.stringify(cfg, null, 2)};\n`;
    res.writeHead(200, { 'Content-Type': 'application/javascript; charset=utf-8', 'Cache-Control': 'no-store' });
    res.end(js);
    return;
  }

  // Normalize URL
  let urlPath = decodeURIComponent(req.url.split('?')[0]);
  if (urlPath === '/') urlPath = '/index.html';

  // Prevent path traversal
  const filePath = path.join(PUBLIC_DIR, urlPath);
  if (!filePath.startsWith(PUBLIC_DIR)) {
    res.writeHead(403);
    res.end('Forbidden');
    return;
  }

  fs.stat(filePath, (err, stats) => {
    if (err || !stats.isFile()) {
      // Try index.html fallback for directory requests
      const indexPath = path.join(PUBLIC_DIR, urlPath, 'index.html');
      fs.stat(indexPath, (err2, stats2) => {
        if (err2 || !stats2.isFile()) {
          // Graceful 404 page — handles Render free-tier cold start
          res.writeHead(404, { 'Content-Type': 'text/html; charset=utf-8' });
          res.end(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="refresh" content="3" />
  <title>UNN Socials — Waking up...</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
      background: #0a1a0a;
      display: flex;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
      color: #e0e0e0;
      text-align: center;
      padding: 24px;
    }
    .card {
      background: linear-gradient(145deg, #0f2a0f, #1a3a1a);
      border: 1px solid #2a5a2a;
      border-radius: 24px;
      padding: 48px 40px;
      max-width: 480px;
      width: 100%;
      box-shadow: 0 24px 80px rgba(0,0,0,0.6);
    }
    .logo { font-size: 28px; font-weight: 700; margin-bottom: 24px; }
    .logo span { color: #ffd700; }
    .icon { font-size: 56px; margin-bottom: 16px; }
    h1 { font-size: 22px; font-weight: 600; margin-bottom: 12px; color: #fff; }
    p { font-size: 15px; line-height: 1.6; color: #a0c0a0; margin-bottom: 24px; }
    .spinner {
      display: inline-block;
      width: 36px; height: 36px;
      border: 3px solid #2a5a2a;
      border-top-color: #ffd700;
      border-radius: 50%;
      animation: spin 0.8s linear infinite;
      margin-bottom: 20px;
    }
    @keyframes spin { to { transform: rotate(360deg); } }
    .btn {
      display: inline-block;
      background: #ffd700;
      color: #0a1a0a;
      font-weight: 600;
      font-size: 15px;
      padding: 12px 32px;
      border-radius: 40px;
      text-decoration: none;
      transition: background 0.2s;
    }
    .btn:hover { background: #ffe44d; }
    .hint { font-size: 13px; color: #608060; margin-top: 16px; }
  </style>
</head>
<body>
  <div class="card">
    <div class="logo">UNN <span>Socials</span></div>
    <div class="icon">⚡</div>
    <div class="spinner"></div>
    <h1>Waking up the server…</h1>
    <p>This page is hosted on a free service that sleeps after inactivity.<br>It should be ready in a moment.</p>
    <a href="/" class="btn" onclick="location.reload()">⟳ Refresh Now</a>
    <p class="hint">Auto-refreshing every 3 seconds &mdash; or tap the button above.</p>
  </div>
</body>
</html>`);
          return;
        }
        const ext = path.extname(indexPath).toLowerCase();
        res.writeHead(200, { 'Content-Type': MIME_TYPES[ext] || 'application/octet-stream' });
        fs.createReadStream(indexPath).pipe(res);
      });
      return;
    }

    const ext = path.extname(filePath).toLowerCase();
    res.writeHead(200, { 'Content-Type': MIME_TYPES[ext] || 'application/octet-stream' });
    fs.createReadStream(filePath).pipe(res);
  });
});

server.listen(PORT, () => {
  console.log(`UNN Socials server running at http://localhost:${PORT}`);
});

