/*
UNN Socials — Node.js static file server + dynamic config generator
Serves the static site and injects environment variables into config.js
at request time, so Render env vars are picked up without a build step.
*/

const http = require('http');
const fs = require('fs');
const path = require('path');

const PORT = process.env.PORT || 3000;
const PUBLIC_DIR = __dirname;

// Default configuration values (overridden by environment variables on Render)
const defaults = {
  WHATSAPP_FLOAT_NUMBER: '2348122104576',
  WHATSAPP_ORDER_NUMBER: '2348123456789',
  BANK_NAME: 'GTBank',
  BANK_ACCOUNT_NAME: 'UNN Socials',
  BANK_ACCOUNT_NUMBER: '0123456789',
  USSD_CODE: '*123*456*',
  CONTACT_EMAIL: 'events@unnsocials.com',
  FORMSUBMIT_KEY: '8d51333da2a9cfabfb087ffb615b7963',
  REDIRECT_URL: 'https://unnsocials.com/thank-you.html'
};

function getConfig() {
  const cfg = {};
  for (const [key, val] of Object.entries(defaults)) {
    cfg[key] = process.env[key] !== undefined ? process.env[key] : val;
  }
  return cfg;
}

const MIME_TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.png': 'image/png',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.webp': 'image/webp',
  '.txt': 'text/plain; charset=utf-8',
  '.map': 'application/json; charset=utf-8'
};

const server = http.createServer((req, res) => {
  // Dynamically serve config.js with env var values
  if (req.url === '/config.js' || req.url === '/config.js?') {
    const cfg = getConfig();
    const js = `/* Generated by server.js from environment variables */\n` +
      `window.SITE_CONFIG = ${JSON.stringify(cfg, null, 2)};\n`;
    res.writeHead(200, { 'Content-Type': 'application/javascript; charset=utf-8', 'Cache-Control': 'no-store' });
    res.end(js);
    return;
  }

  // Normalize URL
  let urlPath = decodeURIComponent(req.url.split('?')[0]);
  if (urlPath === '/') urlPath = '/index.html';

  // Prevent path traversal
  const filePath = path.join(PUBLIC_DIR, urlPath);
  if (!filePath.startsWith(PUBLIC_DIR)) {
    res.writeHead(403);
    res.end('Forbidden');
    return;
  }

  fs.stat(filePath, (err, stats) => {
    if (err || !stats.isFile()) {
      // Try index.html fallback for directory requests
      const indexPath = path.join(PUBLIC_DIR, urlPath, 'index.html');
      fs.stat(indexPath, (err2, stats2) => {
        if (err2 || !stats2.isFile()) {
          res.writeHead(404, { 'Content-Type': 'text/plain; charset=utf-8' });
          res.end('404 Not Found');
          return;
        }
        const ext = path.extname(indexPath).toLowerCase();
        res.writeHead(200, { 'Content-Type': MIME_TYPES[ext] || 'application/octet-stream' });
        fs.createReadStream(indexPath).pipe(res);
      });
      return;
    }

    const ext = path.extname(filePath).toLowerCase();
    res.writeHead(200, { 'Content-Type': MIME_TYPES[ext] || 'application/octet-stream' });
    fs.createReadStream(filePath).pipe(res);
  });
});

server.listen(PORT, () => {
  console.log(`UNN Socials server running at http://localhost:${PORT}`);
});

